# Generated by Django 4.1.1 on 2022-09-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Pasta')),
                ('level', models.IntegerField(default=0, verbose_name='Nível da Pasta')),
            ],
        ),
    ]
