# Generated by Django 4.1.1 on 2022-10-03 13:49

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_folder_level_alter_folder_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='folder',
            name='level',
            field=models.IntegerField(default=0, editable=False, verbose_name='Nível da Pasta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.SlugField(max_length=255, verbose_name='Nome da Pasta'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=core.utils.get_upload_path, verbose_name='Arquivo')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.folder', verbose_name='Pasta')),
            ],
        ),
    ]
